In [1]:
# from datetime import datetime, timedelta
# import json
# import csv
# import glob
# import os
# import io
# import math
# import requests
# import pandas as pd
# # Basic libraries of python for numeric and dataframe computations.
# import numpy as np
# from prometheus_client import start_http_server, Gauge, Enum
# import warnings  # Used to ignore the warning given as output of the code.
# warnings.filterwarnings('ignore')


# data = {}

# userName='betacom5gaas'
# password='5GaaSR0ck$'

# # userName = 'raemis'
# # password = 'password'


# # Get the API file
# response = requests.get('http://10.14.62.10/api/csv/ip_data_record',
#                         auth=(userName, password), verify=False)

In [2]:
# response

In [3]:
generate_profile_report = False

## Connect MySQL 
- Load Data with mysql.connector
- Load Data in Dataframe format

In [27]:
import mysql.connector
import pandas as pd
from pandas_profiling import ProfileReport

db_connection = mysql.connector.connect(
    host="20.94.254.6",
    user="gyan",
    password="5Gaa$2022",
    database="gyan_db"
)

### Simple Query + Print out

In [20]:
mycursor = db_connection.cursor()
mycursor.execute("SELECT * FROM core_stats")

myresult = mycursor.fetchall()

for x in myresult:
    print(x)

('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 14, 55, 27), 2, '0', 45751, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 15, 16, 59), 2, '0', 45901, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 15, 18, 1), 2, '0', 45901, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 15, 24, 2), 2, '0', 45921, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 15, 30, 2), 2, '0', 45940, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 15, 36, 2), 2, '0', 45980, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 15, 42, 1), 2, '0', 46003, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 15, 48, 2), 2, '0', 37907, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 15, 54, 1), 2, '0', 46049, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 0, 2), 2, '0', 46069, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 5, 2), 2, '0', 46095, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 10, 2), 2, '0', 46118, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 15, 2), 2, '0', 46140, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 20, 2), 2, '0', 46164, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 25, 1), 2, '0', 46187, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 30, 2), 2, '0', 46217, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 35, 2), 2, '0', 46250, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 40, 2), 2, '0', 46279, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 45, 1), 2, '0', 46311, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 50, 2), 2, '0', 46341, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 16, 55, 1), 2, '0', 46371, 0, 0, 25, 100, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 0, 2), 2, '0', 46403, 0, 0, 25, 100, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 5, 2), 2, '0', 46433, 0, 0, 25, 100, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 10, 2), 2, '0', 46464, 0, 0, 25, 100, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 15, 2), 2, '0', 46493, 0, 0, 25, 100, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 20, 1), 2, '0', 46525, 0, 0, 25, 100, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 25, 2), 2, '0', 46557, 0, 0, 25, 100, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 30, 1), 2, '0', 46587, 0, 0, 27, 100, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 35, 2), 2, '0', 46620, 0, 0, 27, 100, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 40, 1), 2, '0', 46649, 0, 0, 27, 100, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 41, 51), 2, '0', 46693, 0, 0, 27, 100, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 50, 2), 2, '0', 46744, 0, 0, 27, 86, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 17, 55, 2), 2, '0', 5214, 0, 0, 27, 86, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 0, 3), 2, '0', 46804, 0, 0, 27, 86, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 5, 3), 2, '0', 29221, 0, 0, 27, 86, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 10, 2), 2, '0', 46865, 0, 0, 27, 86, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 15, 3), 2, '0', 46896, 0, 0, 27, 86, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 20, 2), 2, '0', 46926, 0, 0, 27, 86, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 25, 3), 2, '0', 38218, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 30, 3), 2, '0', 46986, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 35, 2), 2, '0', 47016, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 40, 3), 2, '0', 47048, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 45, 2), 2, '0', 47079, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 50, 3), 2, '0', 47111, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 18, 55, 3), 2, '0', 47143, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 0, 2), 2, '0', 47173, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 5, 3), 2, '0', 47204, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 10, 2), 2, '0', 47233, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 15, 3), 2, '0', 47265, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 20, 2), 2, '0', 7378, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 25, 2), 2, '0', 47328, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 30, 3), 2, '0', 47360, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 35, 3), 2, '0', 47389, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 40, 2), 2, '0', 47421, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 45, 3), 2, '0', 47455, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 50, 2), 2, '0', 47487, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 19, 55, 3), 2, '0', 47520, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 0, 2), 2, '0', 47549, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 5, 3), 2, '0', 47580, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 10, 2), 2, '0', 47609, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 15, 3), 2, '0', 47640, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 20, 2), 2, '0', 47670, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 25, 2), 2, '0', 47702, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 30, 3), 2, '0', 47733, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 35, 2), 2, '0', 47762, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 40, 3), 2, '0', 47793, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 45, 2), 2, '0', 47823, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 50, 3), 2, '0', 47855, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 20, 55, 3), 2, '0', 47886, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 0, 3), 2, '0', 47916, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 5, 2), 2, '0', 47947, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 10, 3), 2, '0', 47976, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 15, 2), 2, '0', 48007, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 20, 3), 2, '0', 48040, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 25, 2), 2, '0', 36517, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 30, 3), 2, '0', 48101, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 35, 2), 2, '0', 48130, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 40, 3), 2, '0', 48161, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 45, 3), 2, '0', 23162, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 50, 3), 2, '0', 48227, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 21, 55, 3), 2, '0', 48258, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 0, 2), 2, '0', 48287, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 5, 3), 2, '0', 46184, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 10, 3), 2, '0', 48351, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 15, 2), 2, '0', 48381, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 20, 3), 2, '0', 48412, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 25, 2), 2, '0', 7246, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 30, 3), 2, '0', 48472, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 35, 2), 2, '0', 48503, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 40, 2), 2, '0', 48533, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 45, 3), 2, '0', 48565, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 50, 2), 2, '0', 48594, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 22, 55, 2), 2, '0', 48626, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 0, 3), 2, '0', 48655, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 5, 3), 2, '0', 48685, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 10, 3), 2, '0', 48717, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 15, 3), 2, '0', 48747, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 20, 2), 2, '0', 48779, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 25, 3), 2, '0', 48808, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 30, 2), 2, '0', 48840, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 35, 3), 2, '0', 48870, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 40, 2), 2, '0', 48901, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 45, 3), 2, '0', 35928, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 50, 3), 2, '0', 48964, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 1, 23, 55, 3), 2, '0', 48995, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 0, 2), 2, '0', 49027, 0, 0, 0, 0, 0, 2, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 5, 3), 2, '0', 49057, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 10, 3), 2, '0', 49088, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 15, 2), 2, '0', 49117, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 20, 3), 2, '0', 49148, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 25, 2), 2, '0', 26817, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 30, 3), 2, '0', 49207, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 35, 2), 2, '0', 49239, 0, 0, 0, 0, 0, 1, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 40, 3), 2, '0', 49268, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 45, 2), 2, '0', 49300, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 50, 3), 2, '0', 49329, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 0, 55, 2), 2, '0', 49357, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 0, 3), 2, '0', 49389, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 5, 2), 2, '0', 49419, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 10, 3), 2, '0', 49450, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 15, 2), 2, '0', 49480, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 20, 3), 2, '0', 49511, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 25, 2), 2, '0', 49539, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 30, 3), 2, '0', 49572, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 35, 2), 2, '0', 49600, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 40, 2), 2, '0', 49631, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 45, 3), 2, '0', 49662, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 50, 2), 2, '0', 49691, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 1, 55, 2), 2, '0', 49722, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 0, 3), 2, '0', 49754, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 5, 2), 2, '0', 411, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 10, 3), 2, '0', 49815, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 15, 2), 2, '0', 49844, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 20, 3), 2, '0', 49874, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 25, 2), 2, '0', 27814, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 30, 2), 2, '0', 49935, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 35, 3), 2, '0', 49967, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 40, 3), 2, '0', 49996, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 45, 2), 2, '0', 50027, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 50, 3), 2, '0', 50059, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 2, 55, 3), 2, '0', 50089, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 0, 2), 2, '0', 50120, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 5, 3), 2, '0', 50150, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 10, 3), 2, '0', 50183, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 15, 2), 2, '0', 50215, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 20, 3), 2, '0', 22736, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 25, 3), 2, '0', 50275, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 30, 3), 2, '0', 50305, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 35, 3), 2, '0', 50336, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 40, 2), 2, '0', 18605, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 45, 2), 2, '0', 28027, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 50, 3), 2, '0', 50433, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 3, 55, 3), 2, '0', 50462, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 0, 3), 2, '0', 50492, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 5, 3), 2, '0', 50522, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 10, 3), 2, '0', 50552, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 15, 3), 2, '0', 50585, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 20, 2), 2, '0', 50615, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 25, 2), 2, '0', 50646, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 30, 3), 2, '0', 50675, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 35, 2), 2, '0', 50705, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 40, 2), 2, '0', 50736, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 45, 3), 2, '0', 50769, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 50, 2), 2, '0', 50800, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 4, 55, 2), 2, '0', 50829, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 0, 3), 2, '0', 49194, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 5, 3), 2, '0', 50889, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 10, 3), 2, '0', 50920, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 15, 2), 2, '0', 50952, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 20, 3), 2, '0', 50981, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 25, 3), 2, '0', 51013, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 30, 2), 2, '0', 51043, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 35, 3), 2, '0', 51075, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 40, 2), 2, '0', 51105, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 45, 3), 2, '0', 51140, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 50, 2), 2, '0', 51172, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 5, 55, 2), 2, '0', 51201, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 6, 0, 3), 2, '0', 51233, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 6, 5, 3), 2, '0', 51262, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 6, 10, 3), 2, '0', 51292, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 6, 15, 3), 2, '0', 51323, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 6, 20, 3), 2, '0', 51353, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 6, 25, 3), 2, '0', 51384, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)
('BETAZRPDCOR001', datetime.datetime(2022, 3, 2, 6, 30, 1), 2, '0', 67, 0, 0, 0, 0, 0, 0, 1, 2, 33.3333)

('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 20, 4), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 7, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 35, 3), 0, '0', 54985, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 8, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 20, 3), 0, '0', 66239, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 9, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 0, 2), 0, '0', 15917, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 20, 3), 0, '0', 57455, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 40, 2), 0, '0', 39167, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 10, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 0, 2), 0, '0', 15786, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 11, 55, 2), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 35, 3), 0, '0', 62379, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 12, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 15, 2), 0, '0', 1870, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 13, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 15, 4), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 14, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 10, 3), 0, '0', 27422, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 50, 3), 0, '0', 39641, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 15, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 10, 3), 0, '0', 44549, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 30, 3), 0, '0', 66877, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 50, 2), 0, '0', 8836, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 16, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 10, 2), 0, '0', 21080, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 17, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 5, 3), 0, '0', 39985, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 15, 4), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 25, 2), 0, '0', 10820, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 45, 3), 0, '0', 71032, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 18, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 19, 0, 3), 0, '0', 67057, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 19, 5, 2), 0, '0', 67, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 19, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 19, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 19, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 19, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 19, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 13, 19, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 11, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 11, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 11, 55, 35), 0, '0', 40083, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 0, 3), 0, '0', 53186, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 5, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 40, 3), 0, '0', 35961, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 45, 11), 0, '0', 58257, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 12, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 0, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 5, 4), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 15, 2), 0, '0', 12246, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 20, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 25, 4), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 45, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 50, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 13, 55, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 0, 4), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 5, 2), 0, '0', 50421, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 10, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 15, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 20, 4), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 25, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 30, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 35, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 40, 3), 0, '0', 72702, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)
('BETBELPDCOR001', datetime.datetime(2022, 3, 14, 14, 45, 3), 0, '0', 62314, 0, 0, 0, 0, 0, 0, 0, 3, 0.0)

### Python Dataframe View
Load four Tables from our Gyan Database
1. rrc
2. rru
3. rb
4. rb_per
5. core_stats

In [7]:
rrc = pd.read_sql('SELECT * FROM vlte_rrc_stats', con=db_connection)
rrc.head()

,vlterrcstats_id,bs_name,cell_number,date_and_time_start,date_and_time_end,connes_tab_succ_sum,connes_tab_fail_sum
0,8ABNLRQ3BF,BELLABHQAIR001,1,2022-02-03 23:30:00,2022-02-03 23:35:00,5,0
1,L4F3VKVFK7,BELLABHQAIR001,1,2022-02-03 23:35:00,2022-02-03 23:40:00,8,0
2,JDRG545ZDE,BELLABHQAIR001,1,2022-02-03 23:40:00,2022-02-03 23:45:00,5,0
3,BZY0RJ03TK,BELLABHQAIR001,1,2022-02-03 23:45:00,2022-02-03 23:50:00,1,0
4,NLB0T53RA1,BELLABHQAIR001,1,2022-02-03 23:50:00,2022-02-03 23:55:00,1,1

In [8]:
rb = pd.read_sql('SELECT * FROM vlte_rb_stats', con=db_connection)
rb.head()

,vlterbstats_id,cell_number,bs_name,date_and_time_start,date_and_time_end,drb_dl_th_capacity_sum,drb_dl_th_capacity_avg,drb_ul_th_capacity_sum,drb_ul_th_capacity_avg,drb_max_ul_th_capacity,drb_pdcp_sdu_air_loss_rate_dl_sum,drb_pdcp_sdu_loss_rate_ul_sum
0,4CEJM8YTN7,1,BELLABHQAIR001,2022-02-03 23:30:00,2022-02-03 23:35:00,0,nan,0,nan,0,0,0
1,Q860OB77BQ,1,BELLABHQAIR001,2022-02-03 23:35:00,2022-02-03 23:40:00,0,nan,278667,16392.18,19200,0,0
2,RH8PNI8A0U,1,BELLABHQAIR001,2022-02-03 23:40:00,2022-02-03 23:45:00,0,nan,36652,6108.67,19200,0,0
3,DS0YK0QL8V,1,BELLABHQAIR001,2022-02-03 23:45:00,2022-02-03 23:50:00,0,nan,0,nan,0,0,0
4,UVYE2OMERM,1,BELLABHQAIR001,2022-02-03 23:50:00,2022-02-03 23:55:00,0,nan,0,nan,0,0,0

In [9]:
rru = pd.read_sql('SELECT * FROM vlte_rru_stats', con=db_connection)
rru.head()

,vlterrustats_id,bs_name,cell_number,total_cell_unavailable_time,total_cell_unavailable_time_manual_intervention,total_cell_unavailable_time_fault,date_and_time_start,date_and_time_end
0,WDO6QJTVJN,BELLABHQAIR001,1,18,0,18,2022-02-03 23:30:00,2022-02-03 23:35:00
1,NBVNF7NLAC,BELLABHQAIR001,1,0,0,0,2022-02-03 23:35:00,2022-02-03 23:40:00
2,ROSGWTCYGM,BELLABHQAIR001,1,0,0,0,2022-02-03 23:40:00,2022-02-03 23:45:00
3,58YZRKOZSV,BELLABHQAIR001,1,0,0,0,2022-02-03 23:45:00,2022-02-03 23:50:00
4,8EJ8439XJU,BELLABHQAIR001,1,0,0,0,2022-02-03 23:50:00,2022-02-03 23:55:00

In [10]:
rb_per = pd.read_sql('SELECT * FROM vlte_rb_per_qci_stats', con=db_connection)
rb_per.head()

,vlterbperqcistats_id,bs_name,cell_number,date_and_time_start,date_and_time_end,qci_index,pdcp_traffic_dl_kbps,pdcp_traffic_ul_kbps,rb_dl_Ip_latency,ip_late_samples_dl,pdcp_sdu_air_loss_rate_dl,pdcp_sdu_air_loss_dl,pdcp_sdu_air_total_dl,pdcp_sdu_drop_rate_dl
0,TCROR7XVCV,BELLABHQAIR001,1,2022-02-03 23:30:00,2022-02-03 23:35:00,1,0,0,0,0,0,0,0,0
1,GIWO7JCOQK,BELLABHQAIR001,1,2022-02-03 23:35:00,2022-02-03 23:40:00,1,0,0,0,0,0,0,0,0
2,LLN8N6D3Q1,BELLABHQAIR001,1,2022-02-03 23:40:00,2022-02-03 23:45:00,1,0,0,0,0,0,0,0,0
3,NF7X04YGSC,BELLABHQAIR001,1,2022-02-03 23:45:00,2022-02-03 23:50:00,1,0,0,0,0,0,0,0,0
4,ASEEMHVFJB,BELLABHQAIR001,1,2022-02-03 23:50:00,2022-02-03 23:55:00,1,0,0,0,0,0,0,0,0

In [28]:
core_stats = pd.read_sql('SELECT * FROM core_stats', con=db_connection)
core_stats.head()

,client_id,stats_timestamp,total_attached_user,total_rejected_user,peak_upload_speed,peak_download_speed,enodeb_shutdown_count,handover_failure_count,bearer_active_user_count,bearer_rejected_user_count,total_users,total_dropped_packets,enodeb_connected_count,enodeb_connection_status
0,BETAZRPDCOR001,2022-03-01 14:55:27,2,0,45751,0,0,0,0,0,0,1,2,33.3333
1,BETAZRPDCOR001,2022-03-01 15:16:59,2,0,45901,0,0,0,0,0,0,1,2,33.3333
2,BETAZRPDCOR001,2022-03-01 15:18:01,2,0,45901,0,0,0,0,0,0,1,2,33.3333
3,BETAZRPDCOR001,2022-03-01 15:24:02,2,0,45921,0,0,0,0,0,0,1,2,33.3333
4,BETAZRPDCOR001,2022-03-01 15:30:02,2,0,45940,0,0,0,0,0,0,1,2,33.3333

In [30]:
asset_location = pd.read_sql('SELECT * FROM assets_location', con=db_connection)
asset_location.head()

,asset_id,cell_num,asset_type,asset_lat,asset_long,asset_azimuth,status
0,BETBELLBENB001,1,Indoor radio,47.611902,-122.196841,125,active
1,BETBELLBENB001,2,Indoor radio,47.611902,-122.196841,125,active
2,BETBELPDENB001,1,Indoor radio,47.611904,-122.196682,180,active
3,BETBELPDENB001,2,Indoor radio,47.611904,-122.196682,180,active
4,DFWIRV01ENB001,1,Indoor radio,32.906672,-97.036331,55,active

### Generate Profile Report

In [35]:

generate_profile_report=False
output_file_location = Profile_report_folder_name+str(table)+".html"
table_list = [rrc ,rru,rb,rb_per,core_stats, asset_location ]
tablename_list = ["rrc" ,"rru","rb","rb_per","core_stats", "asset_location" ]
Profile_report_folder_name = "Profile_Reports/"



if generate_profile_report:
    for table,name in zip(table_list,tablename_list):
        

        profile_report = ProfileReport(table)
        output_file_location = Profile_report_folder_name+name+".html"
        
        
        if os.path.exists(csv_filename):
            print("File {} already generated".format(output_file_location))
            pass
        else:
            profile_report.to_file(output_file=output_file_location)
            print("Table ", name," Complete")

Summarize dataset:   0%|          | 0/21 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Table  rrc  Complete

Summarize dataset:   0%|          | 0/22 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Table  rru  Complete

Summarize dataset:   0%|          | 0/26 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Table  rb  Complete

Summarize dataset:   0%|          | 0/28 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Table  rb_per  Complete

Summarize dataset:   0%|          | 0/28 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Table  core_stats  Complete

Summarize dataset:   0%|          | 0/21 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Table  asset_location  Complete

In [38]:
import os

if generate_profile_report:
    for table,name in zip(table_list,tablename_list):

        profile_report = ProfileReport(table)
        output_file_location = Profile_report_folder_name+name+".html"
        
        
        if os.path.exists(output_file_location):
            print("File {} already generated".format(output_file_location))
            pass
        else:
            profile_report.to_file(output_file=output_file_location)
            print("Table ", name," Complete")

File Profile_Reports/rrc.html already generated
File Profile_Reports/rru.html already generated
File Profile_Reports/rb.html already generated
File Profile_Reports/rb_per.html already generated
File Profile_Reports/core_stats.html already generated
File Profile_Reports/asset_location.html already generated

## Data Cleaning

### Deal with nan

In [63]:
import math

test_data_a = 21
test_data_b = -19
test_data_c = float("nan")

print(math.isnan(test_data_a))
print(math.isnan(test_data_b))
print(math.isnan(test_data_c))

False
False
True

In [73]:
rb["drb_dl_th_capacity_avg"]= rb["drb_dl_th_capacity_avg"].apply(lambda x: float(x) if x=="nan" else x)

In [77]:
rb["drb_dl_th_capacity_avg"].value_counts().sort_values(ascending= False)

0.0        454
1233.0       4
1226.0       4
266.8        4
1237.0       3
          ...
1571.68      1
469.45       1
1071.21      1
1360.93      1
228.2        1
Name: drb_dl_th_capacity_avg, Length: 3387, dtype: int64

### Manualy Check

#### rb

In [47]:
rb.columns

Index(['vlterbstats_id', 'cell_number', 'bs_name', 'date_and_time_start',
       'date_and_time_end', 'drb_dl_th_capacity_sum', 'drb_dl_th_capacity_avg',
       'drb_ul_th_capacity_sum', 'drb_ul_th_capacity_avg',
       'drb_max_ul_th_capacity', 'drb_pdcp_sdu_air_loss_rate_dl_sum',
       'drb_pdcp_sdu_loss_rate_ul_sum'],
      dtype='object')

In [79]:
rb.groupby("bs_name")[['drb_dl_th_capacity_sum', 'drb_dl_th_capacity_avg',
       'drb_ul_th_capacity_sum', 'drb_ul_th_capacity_avg',
       'drb_max_ul_th_capacity', 'drb_pdcp_sdu_air_loss_rate_dl_sum',
       'drb_pdcp_sdu_loss_rate_ul_sum']].agg(['mean']).reset_index().round(2)

,bs_name,drb_dl_th_capacity_sum,drb_ul_th_capacity_sum,drb_max_ul_th_capacity,drb_pdcp_sdu_air_loss_rate_dl_sum,drb_pdcp_sdu_loss_rate_ul_sum
,,mean,mean,mean,mean,mean
0,BELLABHQAIR001,inf,inf,inf,inf,inf
1,BELLABHQENB001,inf,inf,inf,0.0,inf
2,BELPROHQENB002,inf,inf,inf,0.0,0.0
3,BETBELARENB001,0.0,0.0,0.0,0.0,0.0
4,BETBELLBENB001,inf,inf,inf,0.0,0.0
5,BETBELPDENB001,inf,inf,inf,inf,inf
6,DFWIRV01ENB001,0.0,0.0,0.0,0.0,0.0
7,DFWIRV01ENB002,0.0,0.0,0.0,0.0,0.0
8,PnP_Outdoor_Test,0.0,0.0,0.0,0.0,0.0

## Helper Functions

In [32]:
def getSummaryTable(df):
    '''
    Input: a Dataframe you want to get some columsn
    Output: a summary table in dataframe format, with 1st column as id, 2nd column as Missing value percentage, third column as Unique value count.

    summary_table= getSummaryTable(df)

    '''

    columns = list(df.columns)
    unique_column = [df[c].nunique() for c in columns]

    missing_number = df.isnull().sum()/len(df)
    missing_number = list(missing_number)

    Columns_Name = list(df.columns)
    summary_table = pd.DataFrame({'Columns_Name': Columns_Name,
                                 'missing_rate': missing_number,
                                  'unique_count': unique_column})

    return summary_table

In [33]:
def getDuplicateColumns(df):
    '''
    Get a list of duplicate columns.
    It will iterate over all the columns in dataframe and find the columns whose contents are duplicate.
    :param df: Dataframe object
    :return: List of columns whose contents are duplicates.
    '''
    duplicateColumnNames = set()
    # Iterate over all the columns in dataframe
    cnt = 0
    for i in range(df.shape[1]):

        # Select column at xth index.
        col = df.iloc[:, i]

        # Iterate over all the columns in DataFrame from (x+1)th index till end
        for j in range(i + 1, df.shape[1]):
            # Select column at yth index.
            otherCol = df.iloc[:, j]

            # Check if two columns at x 7 y index are equal
            if col.equals(otherCol):
                duplicateColumnNames.add(df.columns.values[j])

                print("Pair", cnt, ": ", df.columns[i], " | ", df.columns[j])
                cnt += 1

    return list(duplicateColumnNames)


def remove_duplicate_columns(df):
    '''
    Remove duplicate columns (columns with different name but same values)

    input: a dataframe
    Output: dataframe without duplicate columns

    '''

    duplicate_list = getDuplicateColumns(df)
    col = list(df.columns)
    for i in duplicate_list:
        col.remove(i)

    return df[col]

In [31]:
getSummaryTable(rb_per)

                 Columns_Name  missing_rate  unique_count
0        vlterbperqcistats_id           0.0        440190
1                     bs_name           0.0             9
2                 cell_number           0.0             2
3         date_and_time_start           0.0          3717
4           date_and_time_end           0.0          3717
5                   qci_index           0.0            15
6        pdcp_traffic_dl_kbps           0.0           309
7        pdcp_traffic_ul_kbps           0.0           171
8            rb_dl_Ip_latency           0.0            22
9          ip_late_samples_dl           0.0           619
10  pdcp_sdu_air_loss_rate_dl           0.0             4
11       pdcp_sdu_air_loss_dl           0.0             3
12      pdcp_sdu_air_total_dl           0.0          1060
13      pdcp_sdu_drop_rate_dl           0.0             5

In [30]:
# Check for Duplication Columns - Same value different col name
getDuplicateColumns(rb_per)

[]

## Prepare Data for Time Series Visualization

### Dataset Preparation
-

## Visualization

### Plotly

,vlterbstats_id,cell_number,bs_name,date_and_time_start,date_and_time_end,drb_dl_th_capacity_sum,drb_dl_th_capacity_avg,drb_ul_th_capacity_sum,drb_ul_th_capacity_avg,drb_max_ul_th_capacity,drb_pdcp_sdu_air_loss_rate_dl_sum,drb_pdcp_sdu_loss_rate_ul_sum
0,4CEJM8YTN7,1,BELLABHQAIR001,2022-02-03 23:30:00,2022-02-03 23:35:00,0,nan,0,nan,0,0,0
1,Q860OB77BQ,1,BELLABHQAIR001,2022-02-03 23:35:00,2022-02-03 23:40:00,0,nan,278667,16392.18,19200,0,0
2,RH8PNI8A0U,1,BELLABHQAIR001,2022-02-03 23:40:00,2022-02-03 23:45:00,0,nan,36652,6108.67,19200,0,0
3,DS0YK0QL8V,1,BELLABHQAIR001,2022-02-03 23:45:00,2022-02-03 23:50:00,0,nan,0,nan,0,0,0
4,UVYE2OMERM,1,BELLABHQAIR001,2022-02-03 23:50:00,2022-02-03 23:55:00,0,nan,0,nan,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
29341,BTVEH6I5OL,2,PnP_Outdoor_Test,2022-02-08 23:05:00,2022-02-08 23:10:00,0,nan,0,nan,0,0,0
29342,PY3LPV9NV7,2,PnP_Outdoor_Test,2022-02-08 23:10:00,2022-02-08 23:15:00,0,nan,0,nan,0,0,0
29343,LJNCVMC980,2,PnP_Outdoor_Test,2022-02-08 23:15:00,2022-02-08 23:20:00,0,nan,0,nan,0,0,0
29344,WSNU0EHEUV,2,PnP_Outdoor_Test,2022-02-08 23:20:00,2022-02-08 23:25:00,0,nan,0,nan,0,0,0
29345,0TMVKXZLWH,2,PnP_Outdoor_Test,2022-02-08 23:25:00,2022-02-08 23:30:00,0,nan,0,nan,0,0,0

### Time Series Date time

In [ ]:
# Get the range of data that needs to be processed
# input("Enter record start time (MM/DD/YYYY):")
start_time = (datetime.now() - timedelta(hours=24)
              ).strftime('%m-%d-%Y %H:%M:%S')
# input("Enter record end time (MM/DD/YYYY):")
end_time = datetime.now().strftime('%m-%d-%Y %H:%M:%S')


# print(response)
df = pd.read_csv(io.StringIO(response.text), parse_dates=['opening_time'])

# Select the data in the required range
mask = (df['opening_time'] <= end_time) & (df['opening_time'] >= start_time)
df_new = pd.DataFrame(df[mask])

# Calculate session peak values to Mbps
print(df_new.tx_peak_octets)
DFWIRV01COR001_1_peak_ul_ses = df_new.tx_peak_octets * 0.0000008
DFWIRV01COR001_1_peak_dl_ses = df_new.rx_peak_octets * 0.0000008


# Find max session peak value
DFWIRV01COR001_1_peak_ul = DFWIRV01COR001_1_peak_ul_ses.max()
DFWIRV01COR001_1_peak_dl = DFWIRV01COR001_1_peak_dl_ses.max()

# Calculate total number of packets dropped
DFWIRV01COR001_1_dropped_packets = df_new.tx_total_dropped_packets + \
    df_new.rx_total_dropped_packets
DFWIRV01COR001_1_transmitted_packets = df_new.tx_packets + df_new.rx_packets
DFWIRV01COR001_1_total_transmitted_packets = DFWIRV01COR001_1_transmitted_packets.sum()
DFWIRV01COR001_1_total_dropped_packets = DFWIRV01COR001_1_dropped_packets.sum()
if DFWIRV01COR001_1_total_dropped_packets is None:
    DFWIRV01COR001_1_total_dropped_packets = 0

# print(DFWIRV01COR001_1_total_dropped_packets)
# print(DFWIRV01COR001_1_total_transmitted_packets)

if DFWIRV01COR001_1_total_dropped_packets is not None and DFWIRV01COR001_1_total_dropped_packets != 0:
    DFWIRV01COR001_1_percentage_drop = (
        DFWIRV01COR001_1_total_dropped_packets / DFWIRV01COR001_1_total_transmitted_packets) * 100
else:
    DFWIRV01COR001_1_percentage_drop = 0

# Find total users in the Data Frame
DFWIRV01COR001_1_total_users = df_new.sub_ref_2.nunique()

# Print out the calculated values
print("Peak Upload Speed (Mbps):", DFWIRV01COR001_1_peak_ul)
print("Peak Download Speed (Mbps):", DFWIRV01COR001_1_peak_dl)
print("Percentage Packets Dropped:", DFWIRV01COR001_1_total_dropped_packets)
print("Total Users:", DFWIRV01COR001_1_total_users)